dist: precise
language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk7
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/install-mvn-3.2.5.sh
- $HOME/build-script/travis-ci/nablarch-mvn-build.sh
- $HOME/build-script/travis-ci/upload-mvn-test-report.sh
notifications:
  slack:
    secure: JD5BHNOH3WrvGq/AkC6loZjHhfZDOA0MHijstF8cPWKfJ6ZjJHI7FQizW8jGaXtztiBvXzmmqYjUiFxifrHaY/YnuR0BCspXXq9D4o314JsB7GZIzt3eiCSj3OlfPMV+NIjPMZ46jpGualhAk8SrlPd64bklH/bceHXYRFa9G50J/Y4T2Xya2tpjRMvcOgcEya64RicofqPMaIUhhL1XJRkduI30JdStOOvbnvFwrxBhNsESg3906zIbwuUY9kES+65jqBHwuE22eo08yFkX2GK/XPl0dOZOgd6ofm0stiF3HqgoBY2mW0glgWQ8DhqsvQFtQa08mMSosFAiy7JHgwYjnoQTGteB1bh3WF5/httdeEq/u/n/LaaA7VfwMl1gS78jLlfVStWQe3GJ2CvzavHGEotPVG/GKDgN2l/tpvWSe/SCTcP9iqUhybCRF336pnEeuPjPmv7yRygSKys/0jLyq4DqKvNv/ZrFgDrEbqEN9s62GnzpFVrk0ZU2uw/TrsfkLsBST5PzoCQXaaUdDRaqzVytC8jMSsyp4oNo30ypHcQX7eNQuCEV0xlFB7OLPRrlK5EJ8pVZ1J37hATDUuKltrcfcQtMj4YDLMw9espUF5H6BUdyNdqoM+JmtkDI5A2js5p1H57WFPEkTxm9xGYc3ZIHgCZZL4DCMw2UG9A=
